/*
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See the LICENSE file in the project root for full license information.
 */
#include "stdafx.h"
#include "Tpm2.h"

_TPMCPP_USING

// Windows SDK headers may define this symbol
#ifdef _C2
#undef _C2
#endif

using namespace std;

// *************************************************************************************
//
// NOTE! Do not edit this file, it is auto-generated from the TPM 2.0 Specification
// documents using the TpmTypes_skel.cpp template.
//
// *************************************************************************************

//<<impl>>
