/*++

Copyright (c) 2013, 2014  Microsoft Corporation
Microsoft Confidential

*/
#include "stdafx.h"
#include "Tpm2.h"

_TPMCPP_USING

// *************************************************************************************
//
// NOTE! Do not edit this file, it is auto generated! This source is TpmTypes_skel.cpp.
//
// *************************************************************************************

//<<iml>>