/*++

Copyright (c) 2013, 2014  Microsoft Corporation
Microsoft Confidential

*/
#pragma once
#include "TpmStructureBase.h"

_TPMCPP_BEGIN

// *************************************************************************************
//
// NOTE! Do not edit this file, it is auto generated! This source is TpmTypes_skel.h.
//
// *************************************************************************************

class _DLLEXP_ Tpm2;

//<<types>>

_TPMCPP_END
