""" 
 * Copyright(c) Microsoft Corporation.All rights reserved. 
 * Licensed under the MIT License. 
 * See the LICENSE file in the project root for full license information. 
"""

"""
 * This file is automatically generated from the TPM 2.0 rev. 1.46 specification documents.
 * Do not edit it directly.
"""


from .TpmTypes import *

print('TSS.Py::__INIT__.PY invoked')

if not NewPython:
    FixupEnumerators(NameUnionTagValues)
    FixupEnumerators(TPM_ALG_ID)
    FixupEnumerators(TPM_ECC_CURVE)
    FixupEnumerators(SHA1)
    FixupEnumerators(SHA256)
    FixupEnumerators(SHA384)
    FixupEnumerators(SHA512)
    FixupEnumerators(SM3_256)
    FixupEnumerators(ImplementationConstants)
    FixupEnumerators(Logic)
    FixupEnumerators(TPM_SPEC)
    FixupEnumerators(TPM_GENERATED)
    FixupEnumerators(TPM_CC)
    FixupEnumerators(TPM_RC)
    FixupEnumerators(TPM_CLOCK_ADJUST)
    FixupEnumerators(TPM_EO)
    FixupEnumerators(TPM_ST)
    FixupEnumerators(TPM_SU)
    FixupEnumerators(TPM_SE)
    FixupEnumerators(TPM_CAP)
    FixupEnumerators(TPM_PT)
    FixupEnumerators(TPM_PT_PCR)
    FixupEnumerators(TPM_PS)
    FixupEnumerators(TPM_HT)
    FixupEnumerators(TPM_RH)
    FixupEnumerators(TPM_NT)
    FixupEnumerators(TPM_AT)
    FixupEnumerators(TPM_AE)
    FixupEnumerators(PLATFORM)
    FixupEnumerators(Implementation)
    FixupEnumerators(TPM_HC)
    FixupEnumerators(TPMA_ALGORITHM)
    FixupEnumerators(TPMA_OBJECT)
    FixupEnumerators(TPMA_SESSION)
    FixupEnumerators(TPMA_LOCALITY)
    FixupEnumerators(TPMA_PERMANENT)
    FixupEnumerators(TPMA_STARTUP_CLEAR)
    FixupEnumerators(TPMA_MEMORY)
    FixupEnumerators(TPMA_CC)
    FixupEnumerators(TPMA_MODES)
    FixupEnumerators(TPM_NV_INDEX)
    FixupEnumerators(TPMA_NV)


TPM_HANDLE.NULL = TPM_HANDLE(TPM_RH.NULL)
TPM_HANDLE.OWNER = TPM_HANDLE(TPM_RH.OWNER)
TPM_HANDLE.PLATFORM = TPM_HANDLE(TPM_RH.PLATFORM)
TPM_HANDLE.ENDORSEMENT = TPM_HANDLE(TPM_RH.ENDORSEMENT)

